# Generated by Django 3.1 on 2020-10-07 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beachu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default=None, max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('estab', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comestab', to='beachu.estabs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookuser', to=settings.AUTH_USER_MODEL)),
                ('estab', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookestab', to='beachu.estabs')),
            ],
        ),
    ]
