# Generated by Django 3.1 on 2020-10-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachu', '0002_booking_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='estab',
            new_name='favestab',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='favuser',
        ),
    ]
