# Generated by Django 3.1 on 2020-10-09 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachu', '0003_auto_20201007_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 19, 52, 38, 289827)),
        ),
    ]
