# Generated by Django 3.1 on 2020-10-15 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachu', '0006_auto_20201015_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 18, 13, 36, 651940)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 18, 13, 36, 651940)),
        ),
    ]
