# Generated by Django 3.1.1 on 2020-10-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
    ]
