# Generated by Django 3.0.8 on 2020-08-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Comments',
        ),
    ]
