# Generated by Django 3.0.8 on 2020-08-10 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200807_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='auction',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_addr',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
