# Generated by Django 3.0.8 on 2020-08-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_best_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='best_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7),
        ),
    ]
