# Generated by Django 3.0.8 on 2020-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200810_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='best_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
