# Generated by Django 3.0.8 on 2020-08-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200810_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='best_bid',
        ),
    ]
